// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartGameRequest struct {
	Choice               *wrappers.StringValue `protobuf:"bytes,1,opt,name=choice,proto3" json:"choice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StartGameRequest) Reset()         { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string { return proto.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()    {}
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *StartGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameRequest.Unmarshal(m, b)
}
func (m *StartGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameRequest.Marshal(b, m, deterministic)
}
func (m *StartGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameRequest.Merge(m, src)
}
func (m *StartGameRequest) XXX_Size() int {
	return xxx_messageInfo_StartGameRequest.Size(m)
}
func (m *StartGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameRequest proto.InternalMessageInfo

func (m *StartGameRequest) GetChoice() *wrappers.StringValue {
	if m != nil {
		return m.Choice
	}
	return nil
}

type StartGameResponse struct {
	Show                 *wrappers.StringValue `protobuf:"bytes,1,opt,name=show,proto3" json:"show,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StartGameResponse) Reset()         { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string { return proto.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()    {}
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *StartGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartGameResponse.Unmarshal(m, b)
}
func (m *StartGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartGameResponse.Marshal(b, m, deterministic)
}
func (m *StartGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartGameResponse.Merge(m, src)
}
func (m *StartGameResponse) XXX_Size() int {
	return xxx_messageInfo_StartGameResponse.Size(m)
}
func (m *StartGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartGameResponse proto.InternalMessageInfo

func (m *StartGameResponse) GetShow() *wrappers.StringValue {
	if m != nil {
		return m.Show
	}
	return nil
}

func init() {
	proto.RegisterType((*StartGameRequest)(nil), "ltk.StartGameRequest")
	proto.RegisterType((*StartGameResponse)(nil), "ltk.StartGameResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x29, 0xc9, 0x96, 0x92, 0x4b, 0xcf, 0xcf,
	0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x17, 0x25, 0x16, 0x14, 0xa4,
	0x16, 0x15, 0x43, 0x14, 0x49, 0xc9, 0x40, 0xe5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2,
	0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x60, 0xb2, 0x3a, 0x60, 0x2a, 0x59, 0x37, 0x3d, 0x35, 0x4f,
	0xb7, 0xb8, 0x3c, 0x31, 0x3d, 0x3d, 0xb5, 0x48, 0x3f, 0xbf, 0x00, 0xac, 0x02, 0x53, 0xb5, 0x92,
	0x07, 0x97, 0x40, 0x70, 0x49, 0x62, 0x51, 0x89, 0x7b, 0x62, 0x6e, 0x6a, 0x50, 0x6a, 0x61, 0x69,
	0x6a, 0x71, 0x89, 0x90, 0x09, 0x17, 0x5b, 0x72, 0x46, 0x7e, 0x66, 0x72, 0xaa, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0xb7, 0x91, 0x8c, 0x1e, 0xc4, 0x42, 0x3d, 0x98, 0x83, 0xf4, 0x82, 0x4b, 0x8a, 0x32,
	0xf3, 0xd2, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x83, 0xa0, 0x6a, 0x95, 0x5c, 0xb9, 0x04, 0x91, 0x4c,
	0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x32, 0xe0, 0x62, 0x29, 0xce, 0xc8, 0x2f, 0x27, 0xca,
	0x20, 0xb0, 0x4a, 0xa3, 0x42, 0x2e, 0x6e, 0x90, 0x09, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9,
	0x42, 0x49, 0x5c, 0x9c, 0x70, 0x53, 0x85, 0x44, 0xf5, 0x72, 0x4a, 0xb2, 0xf5, 0xd0, 0xdd, 0x2b,
	0x25, 0x86, 0x2e, 0x0c, 0xb1, 0x5c, 0x49, 0x65, 0x92, 0x23, 0x9f, 0x10, 0xcf, 0xd3, 0x3d, 0x0d,
	0x4f, 0x97, 0x77, 0x3f, 0xdb, 0xb1, 0xe3, 0x59, 0x47, 0x7f, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x78,
	0x95, 0x38, 0xf4, 0xcb, 0x0c, 0xf5, 0x41, 0xa1, 0x6e, 0xc5, 0xa8, 0xa5, 0xc1, 0xe8, 0xc4, 0x12,
	0xc5, 0x54, 0x90, 0x94, 0xc4, 0x06, 0x76, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x14,
	0x7d, 0xfe, 0x8f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	StartGame(ctx context.Context, opts ...grpc.CallOption) (GameService_StartGameClient, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) StartGame(ctx context.Context, opts ...grpc.CallOption) (GameService_StartGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GameService_serviceDesc.Streams[0], "/ltk.GameService/StartGame", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceStartGameClient{stream}
	return x, nil
}

type GameService_StartGameClient interface {
	Send(*StartGameRequest) error
	CloseAndRecv() (*StartGameResponse, error)
	grpc.ClientStream
}

type gameServiceStartGameClient struct {
	grpc.ClientStream
}

func (x *gameServiceStartGameClient) Send(m *StartGameRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServiceStartGameClient) CloseAndRecv() (*StartGameResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartGameResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	StartGame(GameService_StartGameServer) error
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) StartGame(srv GameService_StartGameServer) error {
	return status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_StartGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).StartGame(&gameServiceStartGameServer{stream})
}

type GameService_StartGameServer interface {
	SendAndClose(*StartGameResponse) error
	Recv() (*StartGameRequest, error)
	grpc.ServerStream
}

type gameServiceStartGameServer struct {
	grpc.ServerStream
}

func (x *gameServiceStartGameServer) SendAndClose(m *StartGameResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServiceStartGameServer) Recv() (*StartGameRequest, error) {
	m := new(StartGameRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ltk.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartGame",
			Handler:       _GameService_StartGame_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "game.proto",
}
