// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomRequest struct {
	RoomNickName         *wrappers.StringValue `protobuf:"bytes,1,opt,name=room_nick_name,json=roomNickName,proto3" json:"room_nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetRoomNickName() *wrappers.StringValue {
	if m != nil {
		return m.RoomNickName
	}
	return nil
}

type CreateRoomResponse struct {
	RoomId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

func (m *CreateRoomResponse) GetRoomId() *wrappers.StringValue {
	if m != nil {
		return m.RoomId
	}
	return nil
}

type ComeIntoRoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComeIntoRoomRequest) Reset()         { *m = ComeIntoRoomRequest{} }
func (m *ComeIntoRoomRequest) String() string { return proto.CompactTextString(m) }
func (*ComeIntoRoomRequest) ProtoMessage()    {}
func (*ComeIntoRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *ComeIntoRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComeIntoRoomRequest.Unmarshal(m, b)
}
func (m *ComeIntoRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComeIntoRoomRequest.Marshal(b, m, deterministic)
}
func (m *ComeIntoRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComeIntoRoomRequest.Merge(m, src)
}
func (m *ComeIntoRoomRequest) XXX_Size() int {
	return xxx_messageInfo_ComeIntoRoomRequest.Size(m)
}
func (m *ComeIntoRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComeIntoRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComeIntoRoomRequest proto.InternalMessageInfo

func (m *ComeIntoRoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type ComeIntoRoomResponse struct {
	RoomId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ComeIntoRoomResponse) Reset()         { *m = ComeIntoRoomResponse{} }
func (m *ComeIntoRoomResponse) String() string { return proto.CompactTextString(m) }
func (*ComeIntoRoomResponse) ProtoMessage()    {}
func (*ComeIntoRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *ComeIntoRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComeIntoRoomResponse.Unmarshal(m, b)
}
func (m *ComeIntoRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComeIntoRoomResponse.Marshal(b, m, deterministic)
}
func (m *ComeIntoRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComeIntoRoomResponse.Merge(m, src)
}
func (m *ComeIntoRoomResponse) XXX_Size() int {
	return xxx_messageInfo_ComeIntoRoomResponse.Size(m)
}
func (m *ComeIntoRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComeIntoRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComeIntoRoomResponse proto.InternalMessageInfo

func (m *ComeIntoRoomResponse) GetRoomId() *wrappers.StringValue {
	if m != nil {
		return m.RoomId
	}
	return nil
}

type DescribeRoomsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeRoomsRequest) Reset()         { *m = DescribeRoomsRequest{} }
func (m *DescribeRoomsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeRoomsRequest) ProtoMessage()    {}
func (*DescribeRoomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{4}
}

func (m *DescribeRoomsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeRoomsRequest.Unmarshal(m, b)
}
func (m *DescribeRoomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeRoomsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeRoomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeRoomsRequest.Merge(m, src)
}
func (m *DescribeRoomsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeRoomsRequest.Size(m)
}
func (m *DescribeRoomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeRoomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeRoomsRequest proto.InternalMessageInfo

type DescribeRoomsResponse struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeRoomsResponse) Reset()         { *m = DescribeRoomsResponse{} }
func (m *DescribeRoomsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeRoomsResponse) ProtoMessage()    {}
func (*DescribeRoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{5}
}

func (m *DescribeRoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeRoomsResponse.Unmarshal(m, b)
}
func (m *DescribeRoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeRoomsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeRoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeRoomsResponse.Merge(m, src)
}
func (m *DescribeRoomsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeRoomsResponse.Size(m)
}
func (m *DescribeRoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeRoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeRoomsResponse proto.InternalMessageInfo

func (m *DescribeRoomsResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type Room struct {
	RoomId               *wrappers.StringValue `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomNickName         *wrappers.StringValue `protobuf:"bytes,2,opt,name=room_nick_name,json=roomNickName,proto3" json:"room_nick_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{6}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomId() *wrappers.StringValue {
	if m != nil {
		return m.RoomId
	}
	return nil
}

func (m *Room) GetRoomNickName() *wrappers.StringValue {
	if m != nil {
		return m.RoomNickName
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "ltk.CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "ltk.CreateRoomResponse")
	proto.RegisterType((*ComeIntoRoomRequest)(nil), "ltk.ComeIntoRoomRequest")
	proto.RegisterType((*ComeIntoRoomResponse)(nil), "ltk.ComeIntoRoomResponse")
	proto.RegisterType((*DescribeRoomsRequest)(nil), "ltk.DescribeRoomsRequest")
	proto.RegisterType((*DescribeRoomsResponse)(nil), "ltk.DescribeRoomsResponse")
	proto.RegisterType((*Room)(nil), "ltk.Room")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x29, 0xc9, 0x96, 0x92, 0x4b, 0xcf, 0xcf,
	0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x17, 0x25, 0x16, 0x14, 0xa4,
	0x16, 0x15, 0x43, 0x14, 0x49, 0xc9, 0x40, 0xe5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2,
	0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x60, 0xb2, 0x3a, 0x60, 0x2a, 0x59, 0x37, 0x3d, 0x35, 0x4f,
	0xb7, 0xb8, 0x3c, 0x31, 0x3d, 0x3d, 0xb5, 0x48, 0x3f, 0xbf, 0x00, 0xac, 0x02, 0x53, 0xb5, 0x52,
	0x38, 0x97, 0xa0, 0x73, 0x51, 0x6a, 0x62, 0x49, 0x6a, 0x50, 0x7e, 0x7e, 0x6e, 0x50, 0x6a, 0x61,
	0x69, 0x6a, 0x71, 0x89, 0x90, 0x13, 0x17, 0x1f, 0xc8, 0x4d, 0xf1, 0x79, 0x99, 0xc9, 0xd9, 0xf1,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x32, 0x7a, 0x10, 0x9b, 0xf5,
	0x60, 0x2e, 0xd3, 0x0b, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x0f, 0x4b, 0xcc, 0x29, 0x4d, 0x0d, 0xe2,
	0x01, 0xe9, 0xf1, 0xcb, 0x4c, 0xce, 0xf6, 0x4b, 0xcc, 0x4d, 0x55, 0xf2, 0xe6, 0x12, 0x42, 0x36,
	0xb8, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x94, 0x8b, 0x1d, 0x6c, 0x72, 0x66, 0x0a, 0x51,
	0x46, 0xb2, 0x81, 0x14, 0x7b, 0xa6, 0x28, 0xe9, 0x71, 0x09, 0x3b, 0xe7, 0xe7, 0xa6, 0x7a, 0xe6,
	0x95, 0xe4, 0x23, 0xbb, 0x53, 0x1c, 0xd5, 0x34, 0x4e, 0xb8, 0x7a, 0x5f, 0x2e, 0x11, 0x54, 0xf5,
	0x94, 0x59, 0x2f, 0xc6, 0x25, 0xe2, 0x92, 0x5a, 0x9c, 0x5c, 0x94, 0x99, 0x04, 0xf6, 0x4d, 0x31,
	0xd4, 0x7e, 0x25, 0x0b, 0x2e, 0x51, 0x34, 0x71, 0xa8, 0x3d, 0xf2, 0x5c, 0xac, 0x20, 0xad, 0xc5,
	0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x9c, 0x7a, 0x39, 0x25, 0xd9, 0x7a, 0x60, 0x97, 0x40,
	0xc4, 0x95, 0x1a, 0x19, 0xb9, 0x58, 0x40, 0x7c, 0x32, 0x5d, 0x84, 0x25, 0x86, 0x98, 0x48, 0x8d,
	0x21, 0xa3, 0x77, 0x4c, 0x5c, 0xdc, 0x20, 0x37, 0x04, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a,
	0xa5, 0x70, 0x71, 0x21, 0x62, 0x4c, 0x48, 0x0c, 0xec, 0x66, 0x8c, 0xb4, 0x21, 0x25, 0x8e, 0x21,
	0x0e, 0xf1, 0xb3, 0x92, 0xea, 0x24, 0x47, 0x3e, 0x21, 0x9e, 0xa7, 0x1d, 0xb3, 0x9f, 0xee, 0xde,
	0xf5, 0xac, 0x63, 0xff, 0xcb, 0xe9, 0x5b, 0x9a, 0x2e, 0x3f, 0x99, 0xcc, 0xc4, 0xa7, 0xc4, 0xa9,
	0x5f, 0x66, 0xa8, 0x0f, 0xf6, 0xb6, 0x15, 0xa3, 0x96, 0x50, 0x03, 0x23, 0x17, 0x0f, 0x72, 0xdc,
	0x08, 0x49, 0x40, 0x0c, 0xc4, 0x8c, 0x5e, 0x29, 0x49, 0x2c, 0x32, 0x50, 0xcb, 0xac, 0xc1, 0x96,
	0xbd, 0xd8, 0x3f, 0xfb, 0x69, 0xeb, 0x52, 0x24, 0xcb, 0x54, 0x94, 0xe4, 0xe1, 0x96, 0xe9, 0x57,
	0x43, 0x03, 0xd6, 0x56, 0xab, 0x56, 0x3f, 0x39, 0x3f, 0x37, 0x35, 0x3e, 0x33, 0xaf, 0x24, 0x1f,
	0xe4, 0x84, 0x32, 0x2e, 0x5e, 0x94, 0x68, 0x13, 0x82, 0x58, 0x84, 0x2d, 0x8a, 0xa5, 0xa4, 0xb0,
	0x49, 0x41, 0x1d, 0xa1, 0x37, 0xc9, 0x51, 0x4a, 0x48, 0xe2, 0xd9, 0xfc, 0xa5, 0xcf, 0xe7, 0x74,
	0x3f, 0xdd, 0x3b, 0xf9, 0x69, 0x67, 0x2f, 0xc4, 0x29, 0x4f, 0x3b, 0xa6, 0xbf, 0x58, 0xb8, 0x02,
	0xec, 0x20, 0x6e, 0x21, 0x84, 0xef, 0x9d, 0x58, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x51,
	0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x6f, 0x91, 0x0c, 0xf7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoomServiceClient is the client API for RoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoomServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	ComeIntoRoom(ctx context.Context, in *ComeIntoRoomRequest, opts ...grpc.CallOption) (*ComeIntoRoomResponse, error)
	DescribeRooms(ctx context.Context, in *DescribeRoomsRequest, opts ...grpc.CallOption) (*DescribeRoomsResponse, error)
}

type roomServiceClient struct {
	cc *grpc.ClientConn
}

func NewRoomServiceClient(cc *grpc.ClientConn) RoomServiceClient {
	return &roomServiceClient{cc}
}

func (c *roomServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, "/ltk.RoomService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) ComeIntoRoom(ctx context.Context, in *ComeIntoRoomRequest, opts ...grpc.CallOption) (*ComeIntoRoomResponse, error) {
	out := new(ComeIntoRoomResponse)
	err := c.cc.Invoke(ctx, "/ltk.RoomService/ComeIntoRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomServiceClient) DescribeRooms(ctx context.Context, in *DescribeRoomsRequest, opts ...grpc.CallOption) (*DescribeRoomsResponse, error) {
	out := new(DescribeRoomsResponse)
	err := c.cc.Invoke(ctx, "/ltk.RoomService/DescribeRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServiceServer is the server API for RoomService service.
type RoomServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	ComeIntoRoom(context.Context, *ComeIntoRoomRequest) (*ComeIntoRoomResponse, error)
	DescribeRooms(context.Context, *DescribeRoomsRequest) (*DescribeRoomsResponse, error)
}

// UnimplementedRoomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRoomServiceServer struct {
}

func (*UnimplementedRoomServiceServer) CreateRoom(ctx context.Context, req *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedRoomServiceServer) ComeIntoRoom(ctx context.Context, req *ComeIntoRoomRequest) (*ComeIntoRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComeIntoRoom not implemented")
}
func (*UnimplementedRoomServiceServer) DescribeRooms(ctx context.Context, req *DescribeRoomsRequest) (*DescribeRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeRooms not implemented")
}

func RegisterRoomServiceServer(s *grpc.Server, srv RoomServiceServer) {
	s.RegisterService(&_RoomService_serviceDesc, srv)
}

func _RoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltk.RoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_ComeIntoRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComeIntoRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).ComeIntoRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltk.RoomService/ComeIntoRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).ComeIntoRoom(ctx, req.(*ComeIntoRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoomService_DescribeRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServiceServer).DescribeRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltk.RoomService/DescribeRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServiceServer).DescribeRooms(ctx, req.(*DescribeRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ltk.RoomService",
	HandlerType: (*RoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _RoomService_CreateRoom_Handler,
		},
		{
			MethodName: "ComeIntoRoom",
			Handler:    _RoomService_ComeIntoRoom_Handler,
		},
		{
			MethodName: "DescribeRooms",
			Handler:    _RoomService_DescribeRooms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room.proto",
}
